### ISSUE TITLE
（催更）

### ISSUE THREAD

**Issue by sdttttt** [poly000/poly000.github.io#2]
既然整了个blog一个就好好坚持下来啊（魂淡

**Comment by poly000** [comment]
从来不知道写啥……
甚至忘了怎么用了*

**Comment by poly000** [comment]
TODO： 把Codewars的deSudoku翻译到C并且把我的破实现从迭代改成循环

**Comment by sdttttt** [comment]
emm, 好吧, 这个好像是通过actions工作流部署的, 如果要改造工作流我能帮上忙~🤓
